# Generated by Django 4.2 on 2024-12-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descripcion',
            new_name='description',
        ),
    ]
